### PR TITLE
More flexible issue mode specification

### PR DESCRIPTION
**Pull request by hrobeers**
Instead of just using a bool to specify whether an asset can be issues once or multiple times, this proposal allows specification and combination of a very large set of issue modes **using just one serialized byte** (using bit flags).

If you're unfamiliar with bit flags, make sure to read one of the links below.
[http://www.learncpp.com/cpp-tutorial/3-8a-bit-flags-and-bit-masks/](http://www.learncpp.com/cpp-tutorial/3-8a-bit-flags-and-bit-masks/)
[http://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/](http://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/)

### CODE REVIEW

**Comment by hrobeers** [comment]
The `PEG` issue transaction is still being worked out more in detail, but some testing and validation is needed for that. Nevertheless, this protocol change is crucial for PeerAssets' flexibility and extendability.

Constructs like the `CUSTOM` issue mode are crucial to allow PA implementors to deviate from the standard, with the loss of functionality in the generic tooling, but allowing innovation without needing to spawn a competing asset network.

**Comment by peerchemist** [comment]
While I understand the need for something like this, we still did not hear a proposal that would use this features. For example `PEG` is very very close to `MULTI`. And checking the truth of `PPC balance of issuing address` and `balance of issued assets` should be verified on clients side, not in the protocol. Anyway it covers very specific case when this would actually be used.

**Comment by hrobeers** [comment]
As we don't agree on the `PEG` mode, but we do agree on the change from `issue_once` to `issue_mode`, I'll rewrite this pull request to exclude `PEG` so we can discuss it elsewhere.

**Comment by hrobeers** [comment]
Removed the references to `PEG` mode.
Ready for merge!

**Pull request merged**
